inherit_from: .rubocop_todo.yml

CaseIndentation:
  EnforcedStyle: end

CollectionMethods:
  PreferredMethods:
    find: detect

EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Encoding:
  Enabled: false

EndAlignment:
  EnforcedStyleAlignWith: variable

HashSyntax:
  EnforcedStyle: hash_rockets

Loop:
  Enabled: false

PredicateName:
  Enabled: false

RegexpLiteral:
  Enabled: false

Semicolon:
  AllowAsExpressionSeparator: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  AllowDSLWriters: true
  AllowPredicates: true
  ExactNameMatch: true
