language: ruby
env:
  - CI=true
before_script:
  - "bundle exec rake db:prepare"
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
gemfile:
  - gemfiles/rails52.gemfile
  - gemfiles/rails6.gemfile
notifications:
  recipients:
    - gabriel.sobrinho@gmail.com
    - thiago.pradi@gmail.com
