mysql: &mysql
  adapter: mysql2
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  host: localhost
  password: 

octopus: &octopus
  shards:
    alone_shard:
      database: octopus_shard_5
      <<: *mysql

    postgresql_shard:
      adapter: postgresql
      username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
      password: 
      database: octopus_shard_1
      encoding: unicode
      host: localhost

    sqlite_shard:
      adapter: sqlite3
      database: /tmp/database.sqlite3

    history_shards:
      aug2009:
        database: octopus_shard_2
        <<: *mysql
      aug2010:
        database: octopus_shard_3
        <<: *mysql
      aug2011:
        database: octopus_shard_4
        <<: *mysql

    country_shards:
      canada:
        database: octopus_shard_2
        <<: *mysql
      brazil:
        database: octopus_shard_3
        <<: *mysql
      russia:
        database: octopus_shard_4
        <<: *mysql

    protocol_shard: postgres://<%= ENV['POSTGRES_USER'] || 'postgres' %>@localhost:5432/octopus_shard_2
    # NOTE: add password as the following format if any
    # protocol_shard: postgres://<%= ENV['POSTGRES_USER'] || 'postgres' %>:PASSWORD@localhost:5432/octopus_shard_2

octopus_with_default_migration_group:
   <<: *octopus
   default_migration_group: country_shards

production_raise_error:
  shards:
    history_shards:
      duplicated_shard_name:
        database: octopus_shard_5
        <<: *mysql

    country_shards:
      duplicated_shard_name:
        database: octopus_shard_4
        <<: *mysql

production_replicated:
  replicated: true
  fully_replicated: false

  shards:
    slave1:
      database: octopus_shard_2
      <<: *mysql
    slave2:
      database: octopus_shard_3
      <<: *mysql
    slave3:
      database: octopus_shard_4
      <<: *mysql
    slave4:
      is_replica: false
      database: octopus_shard_5
      <<: *mysql

replicated_with_one_slave:
  replicated: true
  shards:
    slave1:
      database: octopus_shard_2
      <<: *mysql


production_fully_replicated:
  replicated: true
  shards:
    slave1:
      database: octopus_shard_2
      <<: *mysql
    slave2:
      database: octopus_shard_3
      <<: *mysql
    slave3:
      database: octopus_shard_4
      <<: *mysql
    slave4:
      database: octopus_shard_5
      <<: *mysql

octopus_rails:
  replicated: true
  environments:
    - staging
    - production

  staging:
    slave1:
      database: octopus_shard_2
      <<: *mysql
    slave2:
      database: octopus_shard_3
      <<: *mysql

  production:
    slave3:
      database: octopus_shard_4
      <<: *mysql
    slave4:
      database: octopus_shard_5
      <<: *mysql

not_entire_sharded:
  entire_sharded: false
  shards:
    europe:
      database: octopus_shard_2
      <<: *mysql
    canada:
      database: octopus_shard_3
      <<: *mysql
    brazil:
      database: octopus_shard_4
      <<: *mysql
    russia:
      database: octopus_shard_5
      <<: *mysql

modify_config:
  replicated: true
  shards:
    modify_config_read:
      adapter: modify_config
      database: octopus_shard_1
      host: localhost
